config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  resources :books do
    resources :comments
    resources :exchanges
  end 
  match '/books/:id/exchanges/:id/approve', to: 'exchanges#approve', via: 'get'
  match '/books/:id/exchanges/:id/deny', to: 'exchanges#deny', via: 'get'
  resources :dashboard

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates_presence_of :title, :author

  belongs_to :user
  has_many :comments
  has_many :exchanges
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  validates_presence_of :title, :content
  belongs_to :book

  scope :apprend, -> {where(status: true)}
end

app/models/exchange.rb
class Exchange < ApplicationRecord

  enum trade_status: { waiting: 0, approve: 1, deny: -1 }

  belongs_to :user
  belongs_to :book

  scope :wait, -> {where(trade_status: 0)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  before_create :generate_username

  private
  def generate_username
    self.username = self.email.split('@').first
  end


  has_many :books
  has_many :exchanges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = Book.all 
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @comments = @book.comments
    @comments = Comment.where(book_id: @book)
    @comments_status = @book.comments.where(user_id:current_user.id, status:false)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :pagecount, :shareable, :tradeable)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.status = false
    @comment.save

    respond_to do |format|
      format.js
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @book = Book.find(params[:book_id])
  end

  def update
    @comment = Comment.find(params[:id]) 
    if @comment.update_attributes(:status => true)
      redirect_to dashboard_index_url
    else
      render 'edit'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:title, :content)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @book = current_user.books.includes(:comments)
    @exchange = Exchange.all
    @comment = Comment.where(user_id:current_user.id)
    @comment_req = Comment.where(book_id: @book.each {|book| book.id}, status: false)
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def new 
    @book = Book.find(params[:book_id])
    @user = User.find_by_id(@book.user_id)
    @books = current_user.books.where(tradeable: true)
  end

  def create
    @book = Book.find(params[:book_id])
    @exchange = @book.exchanges.build(exchange_params)
    if @exchange.save
      redirect_to dashboard_index_url
    else
      render 'new'
    end
  end

  def edit
    @exchange = Exchange.find(params[:id])
    @user = User.find(@exchange.user_id)
    @book = Book.find(@exchange.offer_book_id)

  end

  def approve
    @exchange = Exchange.find(params[:id])
    @exchange.update_attributes(:trade_status => 1)
    redirect_to dashboard_index_path
  end

  def deny
    @exchange = Exchange.find(params[:id])
    @exchange.update_attributes(:trade_status => -1)
    redirect_to dashboard_index_path
  end

  private
  def exchange_params
    params.require(:exchange).merge(user_id: current_user.id).permit(:user_id, :offer_book_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user.present?
        redirect_to books_url
    else
        @books = Book.where(shareable: true)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :pagecount %>
    <%= form.number_field :pagecount %>
  </div>

  <div class="field">
    <%= form.label :shareable %>
    <%= form.check_box :shareable %>
  </div>

  <div class="field">
    <%= form.label :tradeable %>
    <%= form.check_box :tradeable %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div>
<h1>Books</h1>


<table class="table table-borderless table-hover ">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>User</th>
      
      <th>Show</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.user.username %></td>
        <td><%= link_to 'Show', book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
<%= link_to 'Dashboard', dashboard_index_url %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div >
  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @book.author %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @book.user.username %>
  </p>

 <div>
    <strong>Tradeable:</strong>
    <%if @book.tradeable == true %>
    <p>  <a href="<%= new_book_exchange_path(@book.id) %>" class="btn btn-secondary text-white">Trade </a></p>
    <%else %>
      <%= @book.tradeable %>
    <% end %>
</div>

  <hr>
  <h2>Comments:</h2>
  <%= render @book.comments.apprend %>
  <div class="comments" > 
  <hr>
  <h5> Pending Approval Comments:</h5>
  <%= render @comments_status %>
  </div>
  <hr>

  <h3>Add a comment:</h3>
  <%= form_with(model: [ @book, @book.comments.build ], local: false) do |form| %>
    
      <%= form.label :title %>
      <%= form.text_field :title %>
   
    <p>
      <%= form.label :content %>
      <%= form.text_area :content %>
    </p>

    <button type="submit" class="btn btn-secondary" >
      CREATE
    </button>

  <% end %>

  <hr>

  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Back', books_path %>
</div>

app/views/comments/_comment.html.erb
<div class="comment">   
  <p>     
    <strong>Title:</strong>  
    <%= comment.title %>  
  </p> 
  <p>    
    <strong>Comment:</strong>   
    <%= comment.content %>   
  </p> 
</div>

app/views/comments/create.js.erb
$(".comments").append("<%= escape_javascript(render(@comment))%>");
$("input#comment_title").val('');
$("textarea#comment_content").val('');

app/views/comments/edit.html.erb
<p>
  <strong>Book Information :</strong>
  <%= @comment.book.title %>
</p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= form_for([@book, @comment]) do |list| %>
  <%= list.submit "Approve" %>
<% end %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<hr>
<h2>Comments</h2>
<% @comments.each do |comment| %>  
  <p>
    <strong>Title:</strong>
    <%= comment.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  
  </p>
<% end %>

<hr>

<h2>Add a comment:</h2>
<%= form_with(model: [@book, @book.comments.build], local: true) do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title%>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %><br>
  </p>
<% end %>

<hr>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/dashboard/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row jumbotron text-center">
    <h1 >Dashboard</h1>
      <table class="table table-borderless table-hover ">
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>User</th>
            <th>Show</th>
            <th >Edit</th>
            <th >Destroy</th>
          </tr>
        </thead>
        <tbody>
          <% @book.each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.author %></td>
              <td><%= book.user.username %></td>
              <td><%= link_to 'Show', book %></td>
              <td><%= link_to 'Edit', edit_book_path(book) %></td>
              <td><%= link_to 'Destroy', book_path(book),method: :delete,data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
  </div>
  <div class="row">
    <h4>Comments</h4>
    <table class="table table-borderless table-hover ">
      <thead>
        <tr>
          <th>Book</th>
          <th>Title</th>
          <th>Content</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @comment.each do |comment| %>
          <tr>
          <td><%= Book.find(comment.book_id).title  %></td>
            <td><%= comment.title %></td>
            <td><%= comment.content %></td>
            <td><%= comment.status %></td>
           </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <h4>Comments Requests</h4>
    <table class="table table-borderless table-hover ">
      <thead>
        <tr>
          <th>Book</th>
          <th>Title</th>
          <th>Content</th>
          <th>Status</th>
          <th>Approve</th>
        </tr>
      </thead>
      <tbody>
        <% @comment_req.each do |comment| %>
          <tr>
          <td><%= Book.find(comment.book_id).title  %></td>
            <td><%= comment.title %></td>
            <td><%= comment.content %></td>
            <td><%= comment.status %></td>
            <td> <%= link_to 'Approve ', edit_book_comment_path(comment.book_id, comment.id) %></td>
           </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <h4> Book Requests </h4>            
        <table class="table table-borderless table-hover ">
          <tbody>
          <% @exchange.wait.each do |exchange| %>
            <tr>
              <td><%= Book.find(exchange.offer_book_id).title %></td>
              <td><%= User.find(exchange.user_id).username %></td>
              <td><%= exchange.trade_status %></td>
              <td> <%= link_to 'Show ', edit_book_exchange_path(exchange.book_id,exchange.id) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>

    <div class="col-sm-6">
      <h4>My Book Requests</h4>
      <table class="table table-borderless table-hover ">
        <tbody>
        <% current_user.exchanges.each do |exchange| %>
          <tr>
            <td><%= Book.find(exchange.offer_book_id).title %></td>
            <td><%= User.find(exchange.user_id).username %></td>
            <td><%= exchange.trade_status %></td>

          </tr>
        <% end %>
        </tbody>
    </table>
    </div>
  </div>

<%= link_to 'Home', root_path %>
</div>

app/views/exchanges/edit.html.erb
<div class="container">
  <h2><%= @user.username %> suggested <%= @book.title%></h2>

  <div >
    <%= link_to 'Approve', :controller => :exchanges, :action => :approve %>
    <%= link_to 'Deny', :controller => :exchanges, :action => :deny %>
  </div>

</div>

app/views/exchanges/new.html.erb
<div class =" text-center ">
  <div class="jumbotron">
    <h2 >Exchange of books</h2>
  </div>
  <h4 ><%= "The book named #{@book.title.upcase} a was shared by #{@user.username} " %></h4>

  <%= form_with(model: [ @book, @book.exchanges.build ], local: true) do |form|  %>
    <div class="form-group ">
      <h4 >Please Select Book</h4>
      <%= form.select(:offer_book_id, @books.map{|book| [book.title, book.id]},{},{:class=>" col-4 center"})%>
    </div>
    <button type="submit" class="btn btn-secondary ">Submit</button>
  <% end %>
 
</div>
<%= link_to 'Back to Home', root_path %>

app/views/layouts/application.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!DOCTYPE html>
<html>
  <head >

    <title>Booky</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
  <div class="container">
    <% if user_signed_in? %>   
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<div class="jumbotron text-center">
  <h2>Welcome to Booky</h2>
  <p>Add and share your books</p>
</div>
  
<div class="container">
  <h3 class="text-left">Books</h3>
  <table class="table table-borderless table-hover ">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>User</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.user.username %></td>
          <% if current_user %>
            <td><%= link_to 'Show', book %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>